### ISSUE TITLE
Javadoc for the SDK

### ISSUE THREAD

**Issue by kenptr** [ConnectyCube/connectycube-android-sdk-releases#4]
Hello ConnectyCube team,

Is there javadoc for the SDK?

e.g. https://tokbox.com/developer/sdks/android/reference/

**Comment by TatankaConCube** [comment]
hello @kenptr, we have [documentation](https://developers.connectycube.com/android/) that covers all public API of our SDK. If you found some not documented functionality, please let us know.

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
