### ISSUE TITLE
Timeout error : waiting for stream compression feature 

### ISSUE THREAD

**Issue by shanzeehashmi** [ConnectyCube/connectycube-android-sdk-releases#5]
If  our app is trying to login into chat then in about 10 times it gives error in 4 to 5 times.

The error is : timeout error about 40 sec waiting for stream compression feature.

**Comment by TatankaConCube** [comment]
@shanzeehashmi add, please, more details about your issue: steps to reproduce, the full log from logcat, another info which will helpful for the investigation your issue.

**Comment by TatankaConCube** [comment]
Seems there is no much activity out there. Closing the issue as stale. If it’s still actual - please raise a new one.
