### ISSUE TITLE
User login process takes long time

### ISSUE THREAD

**Issue by vadimpikha** [ConnectyCube/connectycube-android-sdk-releases#6]
executing ConnectycubeChatService#login() takes about 60 sec

**Comment by TatankaConCube** [comment]
@vadimpikha please add more details about your issue: steps to reproduce, a full log from logcat, device's specifications, which you use for tests.

**Comment by vadimpikha** [comment]
I have created minimal app to reproduce that, but it works fine. But it can be reproduced in sample app https://github.com/ConnectyCube/android-messenger-app. Try to send message just after open; you will be able to do it after some time only.
