### ISSUE TITLE
How I can add extra information for ConnectycubeChatDialog?

### ISSUE THREAD

**Issue by vadimpikha** [ConnectyCube/connectycube-android-sdk-releases#7]
I would like to add some extra data for ConnectycubeChatDialog. It has customData field. But I cant figure out how I can add/change this data. Please help

**Comment by vadimpikha** [comment]
And this data are same for all users or not? I would like to add "Archive chats" feature and I want to find a way to add some extra data for chat per user to mark archived chats

**Comment by TatankaConCube** [comment]
1. Before using custom data for dialogs you should create the needed type of data in the admin panel by path Admin panel -> Your app -> Custom -> List -> ADD -> ADD NEW CLASS, then you can use the constructor from SDK `ConnectycubeDialogCustomData(String className)` to create an instance of 'customData' for dialog. Just put needed fields to an instance of this class and set it for dialog instance before creation or updation.
2. Yes, this data related to the dialog model and will be the same for all users. To implement the feature "Archive chats" you can use the field `customData` for `ConnectycubeUser` model by putting there json with needed data (in a string).

**Comment by vadimpikha** [comment]
Thanks a lot!
